alias gst='git status'
alias glg='git lg'
alias gbr='git branch'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcm='git checkout master'
alias gpl='git pull'
alias gpsh='git push'
alias gpf='git push -f'
alias gci='git add . && git commit -m'
alias grb='git rebase'
alias grm='git rebase master'

alias stkin='cd ~/Projects/kinoplan_development && docker-machine start kinoplan; eval $(docker-machine env kinoplan) && bin/start'
alias edital='nano ~/.oh-my-zsh/custom/plugins/rocket-git/rocket-git.plugin.zsh'
alias lint='npm run lint:err'
alias getconfig='mkdir ~/Desktop/kinoplan_config && mkdir ~/Desktop/kinoplan_config/perl-api && mkdir ~/Desktop/kinoplan_config/scala-api && mkdir ~/Desktop/kinoplan_config/planner_advertising && cd ~/Projects/kinoplan_development && cp -R conf ~/Desktop/kinoplan_config && cp -R perl-api/conf ~/Desktop/kinoplan_config/perl-api/conf && cd ~/Projects && cp -R scala-api/conf ~/Desktop/kinoplan_config/scala-api/conf && cp -R planner_advertising/conf ~/Desktop/kinoplan_config/planner_advertising/conf && cd ~/Desktop && zip -r kinoplan_config.zip kinoplan_config && rm -rf ~/Desktop/kinoplan_config'
alias dev3='DEV_API_TARGET=stage3 npm run dev:srv'
alias dev='DEV_API_TARGET=stage240.s1 npm run dev:srv'
